import { Schema } from "effect";

import { TouristAttractionSchema, type TouristAttraction } from "./schema";

const decodeAttraction = Schema.decodeUnknownSync(TouristAttractionSchema);

const rawAttractions = [
  {
    id: "seoul-forest-senior-walk",
    title: "서울숲 느린 산책길",
    region: "서울",
    address: "서울특별시 성동구 뚝섬로 273",
    latitude: 37.5444,
    longitude: 127.0374,
    tourApiContentId: "mock-tourapi-1001",
    imageTone: "park",
    summary: "평탄한 산책로와 벤치가 촘촘한 도심형 휴식 관광지",
    expectedWalkingMinutes: 35,
    slopeLevel: "low",
    stairLevel: "low",
    benchIntervalMeters: 45,
    restroomDistanceMeters: 80,
    restAreaDistanceMeters: 60,
    accessiblePath: true,
    elevatorAvailable: true,
    walkerFriendly: true,
    voiceGuideReady: true,
    cautionNote: "주말 낮에는 사람이 많아 오전 방문이 더 편합니다.",
  },
  {
    id: "gyeongju-daereungwon",
    title: "경주 대릉원 평지길",
    region: "경주",
    address: "경상북도 경주시 황남동 31-1",
    latitude: 35.8346,
    longitude: 129.2186,
    tourApiContentId: "mock-tourapi-1002",
    imageTone: "heritage",
    summary: "넓은 평지 동선과 쉬어가기 좋은 공간이 이어지는 역사 산책지",
    expectedWalkingMinutes: 50,
    slopeLevel: "low",
    stairLevel: "medium",
    benchIntervalMeters: 70,
    restroomDistanceMeters: 130,
    restAreaDistanceMeters: 95,
    accessiblePath: true,
    elevatorAvailable: false,
    walkerFriendly: true,
    voiceGuideReady: false,
    cautionNote: "일부 고분 주변 흙길은 비 온 뒤 미끄러울 수 있습니다.",
  },
  {
    id: "busan-dongbaek-island",
    title: "부산 동백섬 해안길",
    region: "부산",
    address: "부산광역시 해운대구 동백로 67",
    latitude: 35.1526,
    longitude: 129.1522,
    tourApiContentId: "mock-tourapi-1003",
    imageTone: "coast",
    summary: "바다 전망이 좋지만 일부 경사와 계단 우회 확인이 필요한 길",
    expectedWalkingMinutes: 60,
    slopeLevel: "medium",
    stairLevel: "medium",
    benchIntervalMeters: 90,
    restroomDistanceMeters: 180,
    restAreaDistanceMeters: 110,
    accessiblePath: true,
    elevatorAvailable: false,
    walkerFriendly: false,
    voiceGuideReady: true,
    cautionNote: "전망대 방향은 계단 구간이 있어 순환로 일부만 추천합니다.",
  },
  {
    id: "jeju-saryeoni-flat",
    title: "제주 사려니숲 입구길",
    region: "제주",
    address: "제주특별자치도 제주시 조천읍 교래리 산137-1",
    latitude: 33.422,
    longitude: 126.629,
    tourApiContentId: "mock-tourapi-1004",
    imageTone: "forest",
    summary: "숲 그늘이 좋지만 걷는 시간이 길어 체력 안배가 필요한 코스",
    expectedWalkingMinutes: 85,
    slopeLevel: "medium",
    stairLevel: "low",
    benchIntervalMeters: 140,
    restroomDistanceMeters: 260,
    restAreaDistanceMeters: 170,
    accessiblePath: false,
    elevatorAvailable: false,
    walkerFriendly: false,
    voiceGuideReady: false,
    cautionNote: "중간 휴식 지점 간격이 길어 30분 이하 보행자에게는 짧은 구간만 권합니다.",
  },
  {
    id: "gangneung-gyeongpo-lake",
    title: "강릉 경포호 쉬운 둘레길",
    region: "강릉",
    address: "강원특별자치도 강릉시 저동",
    latitude: 37.7952,
    longitude: 128.8965,
    tourApiContentId: "mock-tourapi-1005",
    imageTone: "lake",
    summary: "호수 주변 평탄한 길과 화장실 접근성이 좋은 산책 코스",
    expectedWalkingMinutes: 45,
    slopeLevel: "low",
    stairLevel: "low",
    benchIntervalMeters: 55,
    restroomDistanceMeters: 90,
    restAreaDistanceMeters: 70,
    accessiblePath: true,
    elevatorAvailable: false,
    walkerFriendly: true,
    voiceGuideReady: true,
    cautionNote: "바람이 강한 날에는 호수변 체감 온도가 낮을 수 있습니다.",
  },
  {
    id: "damyang-bamboo-garden",
    title: "담양 죽녹원 입구 산책",
    region: "담양",
    address: "전라남도 담양군 담양읍 죽녹원로 119",
    latitude: 35.3215,
    longitude: 126.9865,
    tourApiContentId: "mock-tourapi-1006",
    imageTone: "bamboo",
    summary: "그늘은 풍부하지만 내부 일부 경사로 때문에 주의가 필요한 대나무길",
    expectedWalkingMinutes: 55,
    slopeLevel: "high",
    stairLevel: "medium",
    benchIntervalMeters: 100,
    restroomDistanceMeters: 120,
    restAreaDistanceMeters: 130,
    accessiblePath: false,
    elevatorAvailable: false,
    walkerFriendly: false,
    voiceGuideReady: false,
    cautionNote: "무릎 부담이 크다면 매표소 인근 평탄 구간 위주로 이용하세요.",
  },
] satisfies Array<unknown>;

export function listMockTouristAttractions(): Array<TouristAttraction> {
  return rawAttractions.map((attraction) => decodeAttraction(attraction));
}

export function listRegions(): Array<string> {
  return Array.from(new Set(listMockTouristAttractions().map((attraction) => attraction.region)));
}
