packages:
  - app/web/*
  - app/mobile/*
  - packages/ui/*
  - packages/domains/*
  - packages/repository/*
  - packages/feature/*
  - template/web/*

ignoredBuiltDependencies:
  - '@tailwindcss/oxide'

onlyBuiltDependencies:
  - esbuild
