packages:
  - app/*
  - packages/ui/*
  - packages/configs/*
  - packages/domains/*
  - packages/feature/*
  - packages/infras/*
  - packages/utils/*
  - template/*

ignoredBuiltDependencies:
  - '@tailwindcss/oxide'
