packages:
  - app/web/*
  - app/mobile/*
  - app/api/*
  - packages/ui/*
  - packages/domains/*
  - packages/infras/*
  - packages/features/*
  - packages/services/*
  - packages/adapters/*
  - template/web/*

ignoredBuiltDependencies:
  - '@tailwindcss/oxide'

onlyBuiltDependencies:
  - esbuild
