import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Footer_1 } from "@ui/shadcn/footer/Footer_1";
import "./globals.css";
import { Providers } from "./providers";
import { ThemeToggle } from "@ui/shadcn/components/ui/theme-toggle";
import { cn } from "@ui/shadcn/utils";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          geistSans.variable,
          geistMono.variable,
          "min-h-screen bg-background text-foreground antialiased transition-colors duration-300"
        )}
      >
        <Providers>
          <div className="flex min-h-screen flex-col bg-background transition-colors duration-300">
            <header className="sticky top-0 z-10 border-b border-border/60 bg-background/90 backdrop-blur transition-colors duration-300">
              <div className="container mx-auto flex items-center justify-end gap-3 px-4 py-4">
                <ThemeToggle className="border-border/60 bg-transparent hover:bg-muted/70" />
              </div>
            </header>

            <main className="container mx-auto flex-grow px-5 py-8 transition-colors duration-300">
              {children}
            </main>

            <footer className="mt-auto border-t border-border/60 bg-muted/40 transition-colors duration-300">
              <div className="container mx-auto px-4 py-6 text-center text-sm">
                <Footer_1 />
              </div>
            </footer>
          </div>
        </Providers>
        {/* 전체 레이아웃 Div 닫힘 */}
      </body>
    </html>
  );
}
